### ISSUE TITLE
Invalid parameter grid_product_home_dir

### ISSUE THREAD

**Issue by Mortinke** [biemond/biemond-oradb#134]
Environment:
Puppetmaster: puppetserver 1.1.3 on CentOS release 6.7 with puppet 3.8.4 and ruby 1.8.7
Client: puppet agent v3.6.2 on Oracle Linux 7.2 with ruby 2.0.0p598

I get the following error message when I use the oradb::dbactions module with db_type=> 'grid':
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter grid_product_home_dir on Db_control[instance control stop upgrdb before patch] at /etc/puppet/modules/oradb/manifests/dbactions.pp:24
```
Calling the oradb::dbactions:
```
$db_actions_db_type = 'grid' 
$db_action_user = 'grid'

oradb::dbactions{"stop $mercateo_oracle::db_name before patch":
  db_type       => $db_actions_db_type,
  oracle_home   => $mercateo_oracle::oracle_home,
  grid_home     => $mercateo_oracle::grid_home,
  user          => $db_action_user,
  group         => 'oinstall',
  action        => 'stop',
  db_name       => $mercateo_oracle::db_name,
}
```

During analyzing the error I noticed that he _grid_product_home_dir_ parameter is defined in _type/db_control.rb_ but not used in the _provider/db_control/*_ files.

**Comment by Mortinke** [comment]
After I disabled the _grid_product_home_dir_ parameter, i get the same error for the the _db_type_ parameter.

**Comment by biemond** [comment]
yeah, the combination with puppet master can be tricky.

but still I don't know why you get this error Invalid parameter grid_product_home_dir 
Can you do a puppet trace & run it in debug?

I know when you update a module you should restart the puppet master and do a puppet run on the master,  the module should be on the primary location.

t should work on every PE or opensource puppet master, customers and I successfully tested orawls on PE 3.0, 3.1, 3.2, 3.3. See also the puppet master vagrant box

For Running orawls module without root/elevated privileges, please use v3.7.0 or higher

But when it fails you can do the following actions.

Check the time difference/timezone between all the puppet master and agent machines.

Update orawls and its dependencies on the puppet master.
After adding or refreshing the  module you need to restart all the PE services on the puppet master (this will flush the PE cache) and always do a puppet agent run on the Puppet master

move module to its primary module location ( /etc/puppetlabs/puppet/module )
Move to the primary module location pup-1515 when the Puppet master loads a Type, it searches the environment that the agent requested. When it loads providers for that type, it searches the default environment instead of the one the agent requested.

**Comment by Mortinke** [comment]
Sorry for the late reply. I already restarted the puppetserver, but I do not execute a puppet run.
I'll try it this afternoon. 

Thanks for the detailed answer!

**Comment by Mortinke** [comment]
After I restarted the puppetserver and executed a puppet run it works without errors.

Sorry for the late feedback and many thanks for the great support!
