### ISSUE TITLE
Enum error on client version

### ISSUE THREAD

**Issue by johmicd** [biemond/biemond-oradb#158]
getting the following error from version 3.0.7 is this working? 

Syntax error at 'Enum'; expected ')' at modules/oradb/manifests/client.pp:54

using the following code:
oradb::client{ '12.2.0.1_Linux-x86-64':
  version                   => '12.2.0.1',
  file                      => 'linuxx64_12201_client.zip',
  oracle_base               => '/u01/app/oracle',
  oracle_home               => '/u01/app/oracle/product/12.2/client',
  user                      => 'oracle',
  group                     => 'dba',
  group_install             => 'dba',
  download_dir              => "/nfs/infsrv_shared/installers/oracle/client/12C/12.2",
  bash_profile              => true,
  remote_file               => true,
  log_output                => true,
}

**Comment by biemond** [comment]
This is working for me, are you using puppet >= 4.4 because version 3 of oradb is only for puppet 4 , version 2 is for puppet3 &4

line 54 is this
Enum['11.2.0.1','11.2.0.4','12.1.0.1','12.1.0.2','12.2.0.1'] $version = undef,

https://github.com/biemond/biemond-oradb-vagrant-11.2-ASM-puppet4_3/blob/master/puppet/environments/development/manifests/client.pp#L100
```
  oradb::client{ '11.2.0.4_Linux-x86-64':
    version                   => '11.2.0.4',
    file                      => 'p13390677_112040_Linux-x86-64_4of7.zip',
    oracle_base               => '/oracle',
    oracle_home               => '/oracle/product/11.2/client',
    ora_inventory_dir         => '/oracle',
    remote_file               => false,
    log_output                => true,
    puppet_download_mnt_point => '/software',
  }
```

or https://github.com/biemond/biemond-oradb-vagrant-12.2-CDB-puppet4_3/blob/master/puppet/environments/development/manifests/site.pp#L227
```
  oradb::client{ '12.2.0.1_Linux-x86-64':
    version                   => '12.2.0.1',
    file                      => 'V839967-01.zip',
    oracle_base               => '/oracle',
    oracle_home               => '/oracle/product/12.2/client',
    ora_inventory_dir         => '/oracle',
    remote_file               => false,
    log_output                => true,
    puppet_download_mnt_point => lookup('oracle_source'),
  }
```

**Comment by johmicd** [comment]
O sorry my bad I see that now.  I moved to 2.0.10 and have got passed that point. thanks!
