### ISSUE TITLE
after the update puppetDownloadMntPoint no longer works

### ISSUE THREAD

**Issue by zmsp** [biemond/biemond-oradb#65]
Hi Edwin, I was using your library to create a docker oracle 12 EE database and it worked until the update. After the update it keeps saying invalid parameter and points to line 71. I am referring to the file located here. https://github.com/biemond/docker-database-puppet/blob/master/puppet/manifests/site.pp

Thanks.

**Comment by biemond** [comment]
Hi,

Thanks I forgot to update that one. I changed all oradb parameters to snake style instead of camelcase
This will retrieve the latest version from  forge.

the quick fix for now is to update the puppetfile and add the previous version to the oradb mod reference
https://github.com/biemond/docker-database-puppet/blob/master/puppet/Puppetfile#L9

Thanks

**Comment by biemond** [comment]
like 

mod 'biemond/oradb', "1.0.35"

**Comment by zmsp** [comment]
Thanks! that worked. Just curious in order for it to work with the latest version, I need to change it to snake_case?

**Comment by biemond** [comment]
yeah, nice

like the readme of oradb
