### ISSUE TITLE
DB 12c CDB and PDB creation error

### ISSUE THREAD

**Issue by weiishann** [biemond/biemond-oradb#75]
Hi all,

I faced some issues while installing a new database.

1. Puppet error output => http://pastebin.com/szR62yx9
2. Installation logs => http://pastebin.com/pa1Eb6Ni
3. init.pp for oradb => http://pastebin.com/wRD27mRR

P.S: Edwin, any place we can donate to buy you a beer? :)

**Comment by biemond** [comment]
Hi,

Can you check the hostname on this host plus it looks like you don't add requires between all the  oradb manifest calls.

plus you also need to call oradb::net before listener

so db_listener requires oradb::net etc.. like in  this CDB example 
https://github.com/biemond/biemond-oradb-vagrant-12.1-CDB/blob/master/puppet/manifests/site.pp#L126

beer is always appreciated :+1:

**Comment by weiishann** [comment]
What do you mean by the hostname on the host? What should I look out for? I have configured it in /etc/hostname.

**Comment by biemond** [comment]
that you have a FQDN, Oracle needs it and test it with `facter fqdn`

**Comment by weiishann** [comment]
It looks fine to me about the FQDN. I went to provision another VM from scratch using the same Puppet master... Another error :)

http://pastebin.com/tMg4EChJ

Where is the 80MB SGA size defined at? Is it as below?
  memory_percentage         => '40',
  memory_total              => '800',

**Comment by biemond** [comment]
You are using a template 

Invalid template file "/install/dbtemplate_12.1_oraDb.dbt". The template data is not in the expected format.

If you just want a database then you can remove the template  attribute 

or make sure everything is ok. Your swap, vm memory etc should be ok. Oracle db utility will check it

The specified shared pool size or SGA size "80MB" does not meet the recommended minimum size requirement "331MB"

https://github.com/biemond/biemond-oradb/blob/master/templates/dbtemplate_12.1.dbt.erb#L45
So set these memory_percentage, memory_total to a higher number because Oracle will auto assign the SGA based on these parameters.

**Comment by weiishann** [comment]
How can I buy you a beer? Do you have paypal or something? Your response time is faster than Oracle support :)

I went to edit the template file using Oracle examples in the $ORACLE_HOME/assistant/dbca and it worked fine. Also tuned up the settings to fix it.

**Comment by biemond** [comment]
Cool man and have fun with it. Drink 1 for me. 

Ciao
